package com.orellana.smartringdemov1

const val RING_DEVICE_NAME = "Demo"
const val MAC_ADDRESS_INTENT_EXTRA   = "MAC_ADDRESS_INTENT_EXTRA"
const val FOREGROUND_SERVICE_NOTIFICATION_CHANNEL_ID = "FOREGROUND_SERVICE_NOTIFICATION_CHANNEL_ID"